token:
  - "\\btoken\\b"
  - "auth_token"
  - "access_token"

key:
  - "\\bprivate[_\\-]?key\\b"
  - "\\bapi[_\\-]?key\\b"
  - "\\bsecret[_\\-]?key\\b"

secret:
  - "\\bsecret\\b"
  - "\\bsecret_key\\b"
  - "\\btop_secret\\b"

filesystem:
  - "\\bfile\\b"
  - "/data/"
  - "/sdcard/"
  - "open\\("
  - "read\\("
  - "write\\("

sensitive:
  - "\\bpassword\\b"
  - "\\bcredential\\b"
  - "\\buser[_\\-]?info\\b"
  - "\\bauth\\b"

network:
  - "http[s]?://"
  - "\\bsocket\\b"
  - "\\bconnect\\b"
  - "\\bip\\b"
  - "\\bGET\\s"
  - "\\bPOST\\s"

external:
  - "\\b8\\.8\\.8\\.8\\b"
  - "\\b1\\.1\\.1\\.1\\b"
  - "external_url"
  - "\\bpublic\\b"

blacklisted_ip:
  - "\\b(?:45\\.|185\\.|103\\.)"
  - "malicious\\.net"
  - "evil\\.org"

ip_address:
  - "\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b"

dns:
  - "\\bresolve\\b"
  - "gethostby"
  - "dns_query"

http:
  - "http[s]?://"

reflection:
  - "Class\\.forName"
  - "Method\\.invoke"
  - "\\breflect"

dex_load:
  - "\\bdexclassloader\\b"
  - "dex_load"
  - "dlopen"
  - "loadLibrary"

native:
  - "\\bnative\\b"
  - "\\blibc\\b"
  - "\\bjni\\b"
  - "execve"
  - "fork"

jni:
  - "\\bjni\\b"
  - "Java Native Interface"
  - "JNIEnv"

code_injection:
  - "injection"
  - "shellcode"
  - "r0payload"
  - "loadDex"

evasion:
  - "bypass"
  - "root[_\\-]?check"
  - "\\bhide\\b"
  - "\\bemulator\\b"
  - "instrumentation"

frida:
  - "\\bfrida\\b"
  - "gum\\."
  - "Interceptor\\.attach"

hooking:
  - "\\bhook_"
  - "intercept"
  - "override"

exfiltration:
  - "upload"
  - "send_data"
  - "write_large"
  - "stream"

c2:
  - "command and control"
  - "c2_server"
  - "checkin"
  - "beacon"
  - "evil\\.org"

data:
  - "payload"
  - "data="

write:
  - "\\bwrite\\b"
  - "fwrite"
  - "FileOutputStream"

accessibility:
  - "accessibilityservice"
  - "accessibility_event"

overlay:
  - "TYPE_SYSTEM_ALERT"
  - "TYPE_APPLICATION_OVERLAY"
  - "drawOver"

clickjacking:
  - "hidden_view"
  - "touch_intercept"
  - "click_invisible"

crypto:
  - "cipher"
  - "encrypt"
  - "decrypt"
  - "\\bRSA\\b"
  - "\\bAES\\b"

weak_crypto:
  - "\\bECB\\b"
  - "\\bDES\\b"
  - "\\bMD5\\b"
  - "\\bBase64\\b"
  - "short[_\\-]?key"

base64:
  - "base64"
  - "=="
  - "decode"

entropy:
  - "[A-Za-z0-9+/]{32,}=="
  - "[A-Za-z0-9+/]{40,}"

unencrypted:
  - "\\bunencrypted\\b"
  - "plaintext"
  - "no_ssl"
  - "http://"

privilege:
  - "system_access"
  - "chmod"
  - "\\bsu\\b"
  - "\\broot\\b"

system:
  - "/system/"
  - "/bin/"
  - "/sbin/"
  - "/dev/"

su:
  - "\\bsu\\b"

root:
  - "root_detect"
  - "isRooted"
  - "check_root"

automation:
  - "monkeyrunner"
  - "uiautomator"
  - "auto_click"

obfuscation:
  - "junk_code"
  - "obfuscate"
  - "packer"

xor:
  - "xor\\s*\\("
  - "\\^"

keylogger:
  - "keypress"
  - "keystroke"
  - "keyevent"

tls:
  - "\\bSSLv3\\b"
  - "\\bTLSv1(\\.2|\\.3)?\\b"
  - "ssl_socket"
  - "tls_handshake"

openssl:
  - "libssl"
  - "libcrypto"
  - "openssl"
  - "BIO_"
  - "SSL_"
  - "EVP_"

encrypted:
  - "\\bencrypt\\b"
  - "\\bdecrypt\\b"
  - "encrypted_data"
  - "crypto_context"

logging:
  - "log\\.(?:d|i|e|w)"
  - "print\\("
  - "System\\.out\\.println"

tracking:
  - "\\bgps\\b"
  - "location_manager"
  - "cell_tower"
  - "\\bgeo\\b"

adb:
  - "\\badb\\b"
  - "usb_debug"
  - "adb_shell"

zip:
  - "\\.zip\\b"
  - "ZipInputStream"
  - "ZipOutputStream"
