---
category_score:
  phishing: 25
  privacy: 20
  surveillance: 20
  crypto_usage: 12
  reflection: 10
  dex_loading: 15
  native_injection: 18
  overlay_abuse: 15
  accessibility_abuse: 15
  overlay_phishing: 25
  otp_interception: 22
  sms_stealer: 20
  browser_injection: 18
  keystore_abuse: 18
  credential_harvest: 25
  network_exfiltration: 25
  data_leak: 15
  malicious_behavior: 30
  system_behavior: 15
  sensitive_string: 12
  network: 10
  exfiltration: 22
  privilege_escalation: 15
  c2: 25
  evasion: 20
  ui_abuse: 15
  spyware: 25
  banking_fraud: 30
  cloud_abuse: 22

tag_score:
  data: 6
  fake_login: 10
  foreground_service: 6
  keylogger: 12
  data_leak: 10
  banking: 10
  microphone: 10
  camera: 10
  heartbeat: 8
  persistence: 10
  frequency: 6
  suspicious: 6
  token: 8
  key: 8
  banker: 15
  dropper: 10
  stealer: 12
  c2: 15
  dropzone: 8
  upload: 8
  exfiltration: 15
  http: 8
  dns: 8
  ip_address: 8
  blacklisted_ip: 12
  network: 6
  external: 4
  mitm: 12
  ssl_unpinned: 12
  tls: 8
  openssl: 8
  encrypted: 8
  unencrypted: 4
  crypto: 8
  base64: 4
  entropy: 6
  weak_crypto: 12
  short_key: 8
  ecb: 12
  iv: 6
  dex: 8
  dex_load: 10
  code_injection: 15
  jni: 8
  hooking: 12
  native: 8
  frida: 12
  reflection: 8
  automation: 8
  obfuscation: 8
  xor: 8
  debug_build: 6
  overlay: 8
  accessibility: 8
  clickjacking: 8
  phishing: 12
  ui_hijack: 12
  system_alert: 6
  webview_abuse: 8
  su: 10
  root: 10
  privilege: 8
  auth: 8
  jwt: 10
  secret: 8
  sensitive: 8
  password: 10
  credential: 8
  filesystem: 6
  system: 6
  write: 4
  adb: 8
  signing_bypass: 12
  keystore: 10
  clipboard: 8
  sms: 8
  accessibility_event: 10
  evasion: 8
  tracker: 8
  native_exec: 12
  dex_reflection: 10
  gate_php: 12

severity_score:
  low: 5
  medium: 10
  high: 20
  critical: 30

path_type_score:
  sensitive: 20
  system_access: 15
  obfuscated_write: 12
  config: 10
  app_storage: 5
  general: 0
  signing_bypass: 15
  keystore_access: 15
